### PR TITLE
* Qt5 compatibility

### PR DESCRIPTION
**Pull request by canercandan**
Thanks to https://github.com/bitcoin/bitcoin/pull/2721/files and http://qt-project.org/wiki/Transition_from_Qt_4.x_to_Qt5#6fc981baf045630af42b49ef0525ace3

### CODE REVIEW

**Comment by phelixbtc** [comment]
Great! I suggest we move the Windows build process to Qt5 and it's packaged MinGW version. It will take a while, though. I can't speak for the Linux/Mac versions.

**Comment by canercandan** [comment]
@phelixbtc, are you talking about the run_qmake.bat file ?

**Comment by phelixbtc** [comment]
@canercandan Nope, that is obsolete from my point of view. I am talking about the easywinbuilder scripts in the contrib folder. If (!) everything works it should not be such a big deal.

**Comment by canercandan** [comment]
@phelixbtc from the file https://github.com/namecoin/namecoin/blob/namecoinq-release/contrib/easywinbuilder/4b_build_qt.bat, it doesnot seem it needs changes to work with qt5, someone has to test on windows.

**Comment by phelixbtc** [comment]
~~On Windows switching to Qt5 would force us to use the Qt5.3 packaged MinGW 4.8.2. It would make the MinGW handling easier quite a bit but unfortunately it has no MSYS included (edit: probably it can be automatically installed). It means quite some change and possibly a lot of effort to work out issues. For now there are other things with higher priority on my list...  Still it would be a good first step if we could merge this PR.~~ Sigh, we will have to switch to the new MinGW anyway as Qt4.8.6 is built with that, too.
Can somebody acknowledge it's working with Qt5 (on Linux)? I tested it to build fine with Qt4.8.5. (and will now test with Qt4.8.6.).

**Comment by itoffshore** [comment]
This QT5 patch builds ok on Alpine Linux 32 bit (so should be ok for everyone else on Linux)

https://github.com/canercandan/namecoin/commit/d51627302890b94dd53992b47e758d38b7387d54 also correctly fixes the miniupnpc issue

**Comment by phelixbtc** [comment]
@canercandan, @itoffshore OK, got it working on windows. Noticed a small issue: the debug window can not be closed via mouse click. Do you see that on Linux, too?
I am not aware of any particular issue regarding miniupnpc...  is this a Bitcoin port?

**Comment by itoffshore** [comment]
My build environment doesn't have X so I only checked namecoin built successfully with QT5. The miniunpnp commit https://github.com/namecoin/namecoin/pull/120# from @canercandan fixes the issue I had with miniupnpc in https://github.com/namecoin/namecoin/issues/41 - it also correctly defines the miniupnpc includes for Linux (same as they were defined in 3.72)

**Comment by canercandan** [comment]
thanks @phelixbtc and @itoffshore for your feedback, if anyone can test on windows it will be just fine.

**Comment by canercandan** [comment]
>  am not aware of any particular issue regarding miniupnpc... is this a Bitcoin port?

@phelixbtc the patch is only applied because of an issue I got while building namecoin, I just refer to the bitcoin code to fix this, not any port here.

**Comment by phelixbtc** [comment]
ACK on the miniupnpc changes, easywinbuilder was patching these includes all the time.

Maybe you missed that comment from me: OK, got it working on windows. Noticed a small issue: the debug window can not be closed via mouse click. Do you see that on Linux, too?

**Comment by phelixbtc** [comment]
OK, I got it fixed. :) 
Will create new separated PRs to the master branch (namecoinq) later/tomorrow.

**Comment by phelixbtc** [comment]
Continued at https://github.com/namecoin/namecoin/pull/122

**Pull request closed without merging**
