### PR TITLE
[OS X] Fix compilation with Clang

### PR DESCRIPTION
**Pull request by Midar**
With this, it's possible to get a Namecoin.app, but it freezes after the splash screen.

### CODE REVIEW

**Comment by cassiniNMC** [comment]
Saved me a few hours of research on those build errors. Thanks a lot, Midar. I had to make a few changes to Makefile, though. See below, step 6.  
The resulting Namecoin-Qt.app does not freeze, but there is a problem with Qt for some reason. lsof -n -i :8334 shows eight connections as expected, and it synchronizes correctly.
Analyzing the process with Activity Monitor.app shows a few suspicious "cerror" events, see http://pastebin.com/hmwfkMMR 
Any Qt experts here?

This is what I did:
1.) If you haven't installed Xcode, open Terminal.app and type llvm-g++ --version
Select "Command Line Developer Tools" in the popup window.
2.) Install Homebrew, see http://brew.sh/
3.) brew install autoconf automake berkeley-db4 boost miniupnpc openssl pkg-config protobuf qt
4.) brew info openssl
should display "openssl: stable 1.0.1h (bottled)" or newer
5.) qmake USE_UPNP=-
6.) Edit the resulting Makefile:
a) Add -L/usr/local/Cellar/berkeley-db4/4.8.30/lib -L/usr/local/Cellar/openssl/1.0.1h/lib
to LIBS directly after $(SUBLIBS) (Do not append it at the end of the line!)
b) Add -I/usr/local/Cellar/berkeley-db4/4.8.30/include at the end of the INCPATH line
7) make
Hundreds of warnings show up. No errors.
Namecoin-Qt.app is being created. Size: 6.3 Megabytes.

**Comment by Midar** [comment]
Hardly a few hours - less than 30 minutes ;). It's a quick port, I didn't even properly fix the inline assembly. The problem there is that it tries to make numbers into a string using #, but # only accepts identifiers - and e.g. 1 clearly isn't one. I have no idea why GCC even accepts that. But then again, it's known to accept broken code. Maybe we could use the MS ASM and use -fms-extensions? Or we change it to not take a number as a parameter, but instead a string with a number, so that ASL(1) becomes ASL("1").

When it freezes, it seems to fetch the blocks, at least debug.log states that. I'll let it run, let's see what happens.

It's not necessary to edit the Makefile if you use brew link -f berkeley-db4. It's a brew problem, not a Namecoin problem. You need to do the same for OpenSSL if you don't want to use the OpenSSL included in Mavericks - which seems to be fine, btw. I used it.

**Comment by cassiniNMC** [comment]
Just in case someone else wants to try a Namecoin-Qt build, there is a wiki page on [how to speed-up the initial 50+ hours' start-up period](https://wiki.namecoin.info/index.php?title=How_to_Speed-up_the_Initial_Program_Start)

**Comment by Midar** [comment]
Don't worry, I just let it run until it downloaded the blockchain. Yet, there will be no UI, even after letting it download, while "bitcoind" (I know it's Bitcoin-Qt, but behaving like bitcoind) is still running.

Couldn't find any debug output from Qt, though.

**Comment by phelixbtc** [comment]
@Midar Just checking: You are aware that there is both namecoind and namecoin-qt in there?

**Comment by slef** [comment]
Same here. It compiles but freezes after the splash screen.
Is there any way to compile and use namecoind on its own for now?

**Comment by cassiniNMC** [comment]
>  Is there any way to compile and use namecoind on its own for now?

Yes, this is much easier. Next week I'm going to write the wiki page about compiling both namecoind
and Namecoin-Qt on OSX. You can get a preliminary makefile for namecoind 0.3.75 here:
http://pastebin.com/W1jqVQRB
For namecoind you do not need this pull request. Make sure you are on the "namecoinq-release" branch, then build:
make -f makefile.osx namecoind
(On Mavericks the Command Line Developer Tools are sufficient. Type llvm-g++ --version and click "Install".)

Back to Namecoin-Qt: The problem is Boost 1.55.
At the moment only Boost 1.49 works with Namecoin-Qt.
Furthermore, this PR108 is based on an old Namecoin-Qt 0.3.73. If you clone this repo and let git combine it with this PR108 the resulting Namecoin-Qt build crashes on start-up.
I'll send a new pull request including Midar's changes but based on 0.3.75 in a few days.

**Comment by slef** [comment]
Thanks a lot for your answer! Do you mean the `namecoinq-release` branch?
I don't see a makefile.osx in the repo, and your pastebin above has been removed. Any suggestions?

**Comment by cassiniNMC** [comment]
> Do you mean the  namecoinq-release  branch?

Yes, indeed. I forgot to add the "q". I've already updated my post.

> I don't see a makefile.osx in the repo, and your pastebin above has been removed.

I need to do a few more tests before it is fit for the repo. And sorry, I messed up the pastebin link. Fixed it.

**Comment by slef** [comment]
Hum on the `namecoinq-release` branch I am still getting some errors:

```
In file included from ./headers.h:96:
./serialize.h:557:36: error: redefinition of default argument
                    int nType, int nVersion = VERSION)
                                   ^          ~~~~~~~
./serialize.h:348:49: note: previous definition is here
                                 int nType, int nVersion = VERSION);
                                                ^          ~~~~~~~
./serialize.h:565:29: error: redefinition of default argument
             int nType, int nVersion = VERSION)
                            ^          ~~~~~~~
./serialize.h:351:34: note: previous definition is here
                  int nType, int nVersion = VERSION);
                                 ^          ~~~~~~~
./serialize.h:585:31: error: redefinition of default argument
               int nType, int nVersion = VERSION)
                              ^          ~~~~~~~
./serialize.h:354:36: note: previous definition is here
                    int nType, int nVersion = VERSION);
                                   ^          ~~~~~~~
```

So I tried on this branch. It just gets stuck at the end:

```
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libdb_cxx-4.8.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libboost_system.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libboost_filesystem.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libboost_program_options.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libboost_thread.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libssl.a'
clang: error: no such file or directory: '/Users/MY_FANCY_USERNAME/namecoincompile/namecoin375/namecoin/deps/lib/libcrypto.a'
make: *** [namecoind] Error 1
```

of course I changed `MY_FANCY_USERNAME` to some existing directory but that's not enough. I installed all dependencies using Homebrew. What am I missing?

**Comment by Midar** [comment]
@phelixbtc Yes, I'm aware there's namecoind and Namecoin-Qt alias Namecoin.app. I deliberately chose to build the latter, because that's what's for the end user. And the namecoind part of it worked fine.

FWIW, wine namecoin-qt.exe works fine. But that was to be expected. Just wanted to mention it as a workaround until we found out what causes the freeze.

**Comment by phelixbtc** [comment]
Any news on this? Maybe maxpower from Bitcointalk could help...

**Comment by Midar** [comment]
@phelixbtc The current state is still that with my patches the namecoind part works, but the Qt part doesn't. Any idea when my PR will be merged?

**Comment by phelixbtc** [comment]
Hmm at least one step forward. Unfortunately I can't really speak for OS X stuff...

**Comment by Midar** [comment]
I pushed a new commit that cleans up the platform define chaos, so that you can build the namecoind binary on OS X now if you remove -Bdynamic and -Bstatic from the Makefile.

I'm also working on porting Namecoin to a proper build system. I'm using autoconf + a Makefile-based build system I wrote (https://github.com/Midar/buildsys) for this. This will make porting much easier, especially to unixish platforms that are similar to Linux, but not identical. This will also solve the problem of getting the libboost library suffix and finding all the necessary libraries, removing all the hardcoded paths. Additionally, this will also get rid of having two build systems: Instead of a Makefile for namecoind and a .pro file for Qt, there will be --with-qt and --without-qt and both will use the same build system. I hope I'm not stepping on anybody's toe with that, but the non existence of a proper build system is quite a pain for packagers, reducing the likelihood of Namecoin getting into distributions. My build system to which I'm porting it is quite packager friendly and it is used by Audacious Media Player, Atheme services and all my own projects, just to list a few. If this is work that's not wanted, please tell me ASAP so I don't waste my time ;).

**Comment by phelixbtc** [comment]
I suggest you wait and discuss this first, maybe on the forum.

**Comment by Midar** [comment]
I already started working on it and actually already have it building namecoind - no changing files or fixing paths on each platform anymore ;).

If you want to have a look at it, look at the master branch of https://github.com/Midar/namecoin - it's still a work in progress, though. Working on the Qt part of it now.

**Comment by Midar** [comment]
I rebased it on the correct branch now (namecoinq), but GitHub still wants to merge it into namecoinq-release. While at it, I did some more platform defines cleanup and changed my previous Clang fix (the removal of one insert()). I remove the other insert() now, as the old one fixed Clang on OS X, but broke Clang on Linux. Now that the right one is removed, it works on both.

Can this please be merged (manually, so GitHub doesn't fuck up by merging it into the wrong branch)?

**Comment by Midar** [comment]
I finally got it working on OS X now. The problem was that Boost's interprocess_recursive_mutex is broken on OS X. I have no idea why, as recursive pthread mutexes behave the same on Linux and OS X. I guess I don't even want to know what exactly they did wrong there, considering that Clang is basically flooding me with warnings about how broken Boost is.

Anyway, since there already was a special case for Windows, the only system not using pthreads, I replaced it with direct pthread mutex calls, which fixes Namecoin-Qt on OS X. I commited it in the master branch of https://github.com/Midar/namecoin. I didn't add it to this PR as it depends on my other PR. I think it could be backported, but that's something I'll only do if my other PR gets rejected, as my other PR makes things significantly easier. Without that other PR, more porting and hacking in the .pro file would be needed.

// Edit: Boost might not be the only culprit here. It seems that locks are used incorrectly as well.

**Comment by taoeffect** [comment]
Just in case it's helpful, I submitted an alternative PR to this that you guys can review (#136). It doesn't build Namecoin-QT, but instead builds `namecoind` with minimal changes (and dependencies via Homebrew): https://github.com/namecoin/namecoin/pull/136

It's:
- `Showing 40 changed files with 342 additions and 214 deletions.`

Vs:
- `Showing 4 changed files with 139 additions and 16 deletions.` (and it's actually less than that, as `Makefile.osx` is a copy of `Makefile` with only a few lines changed).

**Comment by Midar** [comment]
FWIW, https://github.com/Midar/namecoin master incorporates these fixes and the ones from https://github.com/namecoin/namecoin/pull/135, plus one more, building a working Namecoin-Qt.

**Comment by taoeffect** [comment]
Cool, I [commented](https://github.com/namecoin/namecoin/pull/135#issuecomment-48990044) in #135. I don't see a PR for your master branch though? Why's that?

**Comment by slef** [comment]
I downloaded the master branch of https://github.com/Midar/namecoin then

```
$ ./autogen.sh
$ ./configure
$ make
```

Builds without errors. Then

```
$ open Namecoin-Qt.app          
The application cannot be opened because its executable is missing.
```

Any extra step I should do?

**Comment by Midar** [comment]
@taoeffect: Yes, there's no PR as it depends on two other PRs that need to be merged first. I wanted to wait on those first.

@slef: Yes, it does not create a Namecoin-Qt.app yet, but only a namecoin-qt binary. I have no idea where the Namecoin-Qt.app you have is from :). You can just ./src/namecoin-qt and it will work fine. But I plan to add a script that calls make and then creates a .app if this gets merged.

**Comment by slef** [comment]
Hum... not for me:

```
$ ./src/namecoin-qt 


************************
EXCEPTION: NSt3__18ios_base7failureE       
CDataStream::read() : end of data: unspecified iostream_category error       
namecoin in Runaway exception       

Segmentation fault: 11
```

**Comment by Midar** [comment]
That sounds like some broken data being read. Have you maybe experimented with Namecoin on OS X before and had it crashing? Try moving your Library/Application Support/Namecoin folder out of the way and see if it works with a fresh one.

**Comment by phelixbtc** [comment]
This needs to be resubmitted to the "namecoinq" branch (=master). Closing.

**Pull request closed without merging**
