### PR TITLE
CMake build files + Mac OS X Build Support

### PR DESCRIPTION
**Pull request by johngalt33**
With these files you can now build name coin on OS X and potentially linux via cmake.
- the patch should be tested to see if it works on linux (it should)
- the patch assumes mac ports was used to install bdb 5.2

### CODE REVIEW

**Comment by phelixbtc** [comment]
Boy, is this old. Anybody using it? Any objections to closing it?

**Comment by JeremyRand** [comment]
No idea... can indolering comment on this?

**Comment by indolering** [comment]
I'll give it a shot.  Jeremy, next time use @indolering and Github will ping me : )

**Comment by indolering** [comment]
Actually, here's a good question: is it working on Linux?  Does it break windows?

**Comment by phelixbtc** [comment]
Windows user not affected besides the outdated and now wrong readme.md changes in this patch.

**Comment by phelixbtc** [comment]
Spring cleaning: @indolering are you still looking into this?

**Comment by indolering** [comment]
The problem is that 10.9 and possibly the latest version of Xcode make changes to the C compiler settings which fucks up the boost libraries.  Even the mainline Bitcoin client is unable to build on 10.9 right now.

Ugh, I just haven't had time to setup a 10.8 or 10.7 VM install and try it out.  I've posted this PR on IRC, the forums, the Namecoin Subreddit, and a couple of OS X devs (@chipselecta and cassini) asking for help.

What's the status on the Libcoin port?

**Comment by phelixbtc** [comment]
Closing for now. I doubt we will use cmake and we can still reopen.

**Pull request closed without merging**
