### PR TITLE
Legacy license date

### PR DESCRIPTION
**Pull request by blrhc**
update for clarity

### CODE REVIEW

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please explain why I shouldn't close this PR as obvious spam.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZnmVJAAoJELPy0WV4bWVwe+AQAJjGMeMV/cGMeXFjUwv0c5KG
5cmu/WGsvyBCvQgeiwNKqWH7zgs3MjlU/Z7YEHao3GQVUeDS1QD99mG82v6cJliI
qNWxcWjM9LBNEzZc5KTOMrj2rsJgihiVkEnhTsn5k9tEy+B0zi4+p+om1RbJ9Q3q
8Wrh4sYKJ4IQluPUlgPUmYIadqi2cocDPeFGBOgceVwr+BpLQP5Dx3w8DY06QEGJ
ctrhA8iWczHZeWO94C+fkmzBo0+RgKeNxmY4CSukp1Sz8fgKPvdqGJNp00DJ3mTV
Sp3FK0MoLH0GYCSE25QqXM3f+EN5cB/81p1VCD0/1wdEcBGPq6YwJxlWtFewHKW9
UoQANR9lD+OQh2z+b5YoBoeJ3vItTS8835wbflI8xLnxIByMi4D1RYomtivxjR5k
/SwfPSsR9VdJBV96jUW6busSOQNmz6j69xiiAum5x8XIy4k6SLNW7DvoRsOdfMnv
JiXpnb70kDXhZ366/guBcKMM5beEyPFdxA/Xt/71L/WkTd8LS0cq36N5E2aUF1kK
2Sqs70mOBrTrmhas5atKIliq1YvtSwwzj6i3Rl4PjSjXkr5s/O/tkHCtAjL5pG4M
O6S0hh7elfhPHqKDwOBP6fJXV4gigcYasDCTVC0qPQCpsniIuTmjOGvGOo4OX29R
sDfaikLg69yhCgqkginO
=fsRp
-----END PGP SIGNATURE-----

**Comment by blrhc** [comment]
Even the old LICENSE files should aim to be kept up to date.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ben Holden-Crowther:
> Even the old LICENSE files should aim to be kept up to date.

The last commit in this repo is in 2015.  How would it be
non-fraudulent to claim that parts of it are copyright in the
2016-2017 range?

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZnprpAAoJELPy0WV4bWVwOu4QAIn60Q84sh2VL86MFHPmH2jy
KaU0okzHC1LHAajH21xAblWFgtQAKjhCF+7L7viczvl+65t7Uq/+Yy1u1AdR1ZpR
CyGhjulik1o3Lm+ZbrhKFah+ZP2oa/L5M3dbi9+wPA40xI3WL/Xe3XO5E0GoN3h8
yGy9k1/p7wow3yRYdNxCG0eso7memtQICK2ul57W7z4y4xWdgMMLjOkYdL59wMd6
TaWaNSkicbsb8gwTXqG6Y8fjp6prLRIKKUDv7TJsqiuHXH32uHHWZfOVWjMQCdgt
UD6+cv8Mp3287bW+W+YZDWGh+xP0QX3AtKJpbfs/6Adgp5TmqXwBmOoab8L7d3kJ
a1KprTnxfu2zeT3qjQPbp4vjZ4Mwxq76zA/zkG8MUI9O3ySM7lmTs97k/+AIYerC
DOnMu7r+91LKdlxbirA0W631ouesQn2O6nTia7Zr2vQalwOj1wDGdbvwLTe/BAZk
l9jhz2LIhCzyRpny9rPLArki/X+46zBPhForBiYY4T14d2GsdhNaK9UEeHN2mWoA
9cdXFlLkP/fZd/L2yC3MDzmvIwIH2qwNy3mwvJMm0zTIj22zf6qNKca+HhWURNTP
N3noKui7mHm2JF0PO9+Gxz253/DpPr/Buy80vugN1Uv8FLxy/80VR/qIZj6JYZF1
Q4mPQUUA3L20JttNP7f1
=69Rx
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
Closing this as obvious spam since OP has vanished.

**Comment by blrhc** [comment]
_If we could see ourselves as others see us, we would vanish on the spot._

**Pull request closed without merging**
