### PR TITLE
Add a proper build system

### PR DESCRIPTION
**Pull request by Midar**
This adds a proper build system, replacing the current 3 hackish build system that are platform dependent and mostly need to be edited in order to compile Namecoin, removing the triplication of the list of flags and files to compile.

It is based on autoconf and a Makefile-based build system I wrote (https://github.com/Midar/buildsys), offers the configure flags --without-miniupnpc and --without-qt, decides whether to build namecoind or Namecoin-Qt based on the latter flag and searches for all dependencies so that the user does not need to edit files anymore.

The build system is used by various projects already, including Audacious Media Player, almost all Atheme projects and almost all ObjFW-related projects, including ObjFW itself, so it is known to not only be easy to use for packagers, which was a design goal form the start, but also known to be highly portable, which even was the primary goal from the start, thus making it much more likely Namecoin will be imported into distributions or ported to new platforms.

I tested Namecoin with the new build system on OS X and Linux, I could not test it on Windows yet, as I currently don't have a Windows box, but I'm confident it will work. I'm also going to try it on all 3 major BSDs - this will even put Namecoin ahead of Bitcoin, which is still a major pain on for example NetBSD.

This PR also incorporates https://github.com/namecoin/namecoin/pull/108, as I had to use something that does compile as the base, of course.

### CODE REVIEW

**Comment by domob1812** [comment]
This seems quite invasive and I've not yet tested it.  However, in general, I'm not opposed to any changes in the build system that improve the situation.

**Comment by Midar** [comment]
The changes to the code are actually minimal: config.h is included in every source file (autoconf creates a config.h instead of creating a lot of -DFOO that are added to the command line) and #include "ui_foo.h" is changed to #include "foo.ui.h". The reason for this is that while GNU make can create rules for creating files with prefixes, this is not really portable and I wanted to keep the Makefiles as portable as possible (as they are right now, they work with GNU make, FreeBSD make, NetBSD make and OpenBSD make). Same for moc_\* → *.moc.cc. The extension was changed from .cpp to .cc, as my build system has no rule for .cpp. I could have added a rule for .cpp, but I left that out deliberately, as the correct extension for C++ is .cc, while .cpp is an extension for C++ that was made popular by Microsoft (.cxx would work as well). Git can handle those renames quite well (if you look at the diff from the command line with eg. git show, don't forget to specify -M).

So what is left is the import of the build system itself, which accounts for 90% of the code in the commit. Which itself again consists of 90% of files import from the autoconf/automake distribution (config.sub, config.guess, install-sh). So if you ignore everything that is not Namecoin-specific, you can actually reaad the whole diff in under 10 minutes :).

**Comment by domob1812** [comment]
Is it actually necessary to import the autotools files?  I usually keep config.sub, config.guess and the likes (which are created by "automake -a") out of the version control system.  If this is not necessary for your system due to some reasons, please do so here, too.  You can provide a shell script "autogen.sh" that builds these.  I think it is reasonable to assume that people who want to use the Git sources need to have autotools installed and can have these files created.  Only source tarballs should include the generated files.

**Comment by Midar** [comment]
I import those as automake can install them, but automake is actually not used. If GNU would finally move aclocal from automake into either autoconf or make it an extra package, there would be no dependency on automake at all.

They are also a little bit patched. I copied those from https://github.com/Midar/objfw, where I use the newest upstream ones and always apply my patchset, which adds support for new platforms. For example, with those you can compile for the PSP (irrelevant for Namecoin, though) and it adds support for ARM64 (how Apple calls AArch64, would be useful if you want to run namecoind on your iPhone).

I think having them in the repo is ok since they're not actually generated, but just imported. They rarely change and by importing them, you have a well defined environment.

**Comment by phelixbtc** [comment]
How will the windows build be affected by these changes? especially in regard to config.h?

**Comment by Midar** [comment]
I have not tested Windows builds (I have no Windows machine at the moment, but this build system is known to work well on Windows, even supporting some Windows-only quirks like implibs so plugins can link back the application), but they should work just fine. You can either issue the normal ./configure && make && make install in MinGW, or you can cross-compile using ./configure --host=i686-w64-mingw32 (when using MinGW w64). I don't see what config.h has to do with it. config.h just has the defines which ./configure added (e.g. GUI, USE_UPNP, …). It could also be expanded to feature checks, e.g. check for somefunction() and then in the code #ifdef HAVE_SOMEFUNCTION can be used.

**Comment by JeremyRand** [comment]
@Midar Just checking, does this make Namecoin-Qt work properly on OS X?

**Comment by Midar** [comment]
@JeremyRand After this, one more patch is needed. If you use https://github.com/Midar/namecoin, you get a working Namecoin-Qt, that still has _some_ dead lock issues left. I experienced a dead lock after changing a domain. But it's a huge step forward already. You can view your transactions and everything.

**Comment by taoeffect** [comment]
OMG how I hate autoconf tools but a proper build system is something that would be very much appreciated. Just wish it wasn't autoconf... Maybe consider the simpler [premake](http://industriousone.com/premake)? (latest update is [this from 2013](http://industriousone.com/topic/premake-44-beta5-now-available) so it still seems alive.)

**Comment by domob1812** [comment]
What's wrong with autotools?  I think they make up a great build system (although I'm not sure how well it works on Windows).  I'd definitely like using autotools in the future - although I'm not sure if it is really necessary to import such a complex system to do that.

**Comment by taoeffect** [comment]
> What's wrong with autotools? I think they make up a great build system (although I'm not sure how well it works on Windows). I'd definitely like using autotools in the future - although I'm not sure if it is really necessary to import such a complex system to do that.

Well, you said it yourself, it's "such a complex system". I am not a fan of complexity, especially when it's unnecessary. Autotools/autoconf involves dealing with very complicated and unreadable configuration files (and many of them). Having used simpler build systems I know there are better solutions out there. Premake also appears to have official Windows support. It's about minimizing unnecessary headache.

**Comment by taoeffect** [comment]
Is anyone going to actually check the thousands of lines of autoconf configuration files in this PR to ensure that no backdoors were introduced? If the answer is "no", then maybe we should reconsider it in favor of a [build system](http://industriousone.com/topic/premake-44-beta5-now-available) that someone can actually verify (with no disrespect meant toward @Midar; autoconf is unfortunately "standard stuff" and a build system is very much appreciated).

**Comment by domob1812** [comment]
@taoeffect: Note that with "autotools", I did mean stock autoconf/automake, while with "complex system" I meant what is done in this PR.  These two are not necessarily linked together.  I would definitely welcome a build system that relied on stock autotools with just a couple of Makefile.am files, but I'm not sure if it is a good idea to include _this_ build system - which is complex and needs thousands of lines, as you pointed out.

**Comment by Midar** [comment]
Actually, this is not autotools, this is autoconf + a Makefile template that is included from Makefiles. It keeps the ugliness of automake and libtool out of the build system, while using the good parts (autoconf). There's still no viable alternative to autoconf, even CMake's checks are far inferior. And it does have the huge advantage of not adding unnecessary and huge dependencies.

The system is actually quite simple and not really complex. automake is much more complex. libtool alone is much more complex. The buildsys.mk file does seem long, but if you look closer, you'll see that it's a lot of repetition for different file types.

I do understand the concerns about backdoors, but actually, those are not necessary: This can be reviewed in less than half an hour, in full. Because you don't need to review everything, but only differences:

For the imported files install-sh, config.sub and config.guess, just diff them to your local versions of them that come shipped with automake. You'll notice that only a few platforms are added. Less than 20 lines of diff.  
For buildsys.mk, you can diff that against the version from various projects that use it. If you still think all these projects would not be able to spot a backdoor in it, you can even review it in about half an hour. This actually comes from the days when I was an Audacious developer, so this has been in Audacious for years, verified by lots of other developers and distribution packagers. Including a backdoor would also ruin my reputation and I would possibly even lose my job. If you look at the commits, you'll see that I do them out in the open, with my full name, not hiding behind a pseudonym, so I could even be held accountable if I would include a backdoor.

I hope this could clear a little of the confusion :).

Oh, and I'm of course always more than happy to answer any question about this build system, and should this be merged of course willing to maintain it and improve on it :). I have a long tradition of doing this for the Audacious / Atheme guys.

// Edit: For the Windows / premake part: This does work on MinGW. So as long as premake doesn't support generating Visual Studio files, it has no advantage over this. It's actually one of the only advantages I see in CMake: Generating Visual Studio and Xcode project files. However, these were never convincing enough for me to accept all the trouble that CMake brings with it, and I do consider writing either a target or a small script that could create Visual Studio / Xcode project files from the Makefiles.

**Comment by indolering** [comment]
Cottons was able to backport Bitcoin's autotools build system.  If Domob is comfortable with autotools, then I say we keep to autotools.

**Comment by indolering** [comment]
Cottons previous [autotools port](https://github.com/chipselecta/namecoin-qt), see /doc.  I believe that the problems I had stemmed from 10.9's Clang/Boost issues.

**Comment by indolering** [comment]
I'm rather frustrated by this PR request.  On the one-hand, we are basically abandoning this repo in favor of Libcoin and any mainline client will be a reimplementation on Bitcoin proper based on Devcoin.  Switching over to this would cost us a lot of time and energy.

We also desperately need a trusted GUI version for OS X and Midar claims that it's close to working.  If you can get OS X working, then perhaps this could be of use.

However, I really wish you could redirect your efforts Midar.  Perhaps that's our fault for not presenting things properly.

**Comment by Midar** [comment]
Well, it's working, but there are a few dead-locks which seem to happen to work on Linux, but freeze on OS X. Maybe someone more familiar with the Namecoin code can spot them, I haven't found the source yet.

What exactly makes you unhappy with my direction? That it's basically more work before switching to libcoin?

**Comment by indolering** [comment]
It's a new build system that almost works on OS X for a codebase that is going to be abandoned.

**Comment by JeremyRand** [comment]
Is anyone able to review this?  I agree with @indolering that we should be focusing efforts on a rebase, but if this PR is an improvement, it would be useful to get it reviewed.  @domob1812 and/or @ryancdotorg ?

**Comment by phelixbtc** [comment]
It seems to me the chances of this getting merged are small. About to close. Sorry.

**Comment by Midar** [comment]
Well, this is _very_ unfortunate, as the commits after this PR make the GUI work on OS X.

**Comment by indolering** [comment]
@Midar You are saying OS X is building now?

**Comment by Midar** [comment]
With my branch, it's not only building, but actually running. But this PR is a prerequisite for that.

**Comment by JeremyRand** [comment]
I would like to see it get merged if someone can review it.  OS X support is important.

**Comment by indolering** [comment]
> With my branch, it's not only building, but actually running. But this PR is a prerequisite for that.

@Midar So you've solved the following problem?

> Well, it's working, but there are a few dead-locks which seem to happen to work on Linux, but freeze on OS X. Maybe someone more familiar with the Namecoin code can spot them, I haven't found the source yet.

**Comment by Midar** [comment]
I have not looked further into them, but you can start the GUI and use it. The only problem is that some operations lock up the GUI and I haven't found out why yet. But this seems to be a general problem with Namecoin and not with OS X, as when I add some debug code to the lock classes wrapping the locks, I see that it's over-releasing locks and deallocating still-locked locks - both are of course completely undefined, even on Linux, and it's pure luck that it works right now on Linux and Windows. OS X seems to be less forgiving there.

**Comment by sdgathman** [comment]
Why not have the debug code ignore over-releases and defer early deallocations, while logging the offending code?  That would let it work more reliably, while facilitating cleaning up the logic.

**Comment by indolering** [comment]
@Midar Have you looked at Libcoin-QT?  Micheal (Libcoin's lead dev) said it would only take a couple of days to get building and he would be happy to advise.  That's a project that would be _amazingly_ helpful.

The only reason I see for using this patch is for a special, OS X only branch.  I don't think it makes sense for Domob and Phelix to re-engineer their build process on code that we are abandoning.  Maybe you can try sdgathman's suggestion, but unless this is working on OS X, then I don't see a reason to use it.

**Comment by phelixbtc** [comment]
What indo said. Maybe as a compromise if it works you could move it into contrib like the EasyWinBuilder stuff.

**Pull request closed without merging**
