### PR TITLE
Autotools backport

### PR DESCRIPTION
**Pull request by indolering**
Backport of Bitcoin's Autotools, fixes OS X build issues.

### CODE REVIEW

**Comment by khalahan** [comment]
Has somebody tested this pull request ?

**Comment by indolering** [comment]
I've only had minor troubles on OS X but got it working for the non GUI.  This is owning largely to my stupid configs, OS X's lack of a coherent dependency management system, and my not caring enough to test the GUI component : P

I cannot speak for other architectures.  I would ask on IRC.

**Comment by indolering** [comment]
I will try building the GUI version on the OS X dev machine tonight.  If you can get it to build on Linux, we are good to go.

**Comment by indolering** [comment]
Alright, I thought my build troubles earlier were my own fault, but I cannot get this to build even on a fresh dev machine.  Gist with log here: https://gist.github.com/nmcbot/9403870

Happy to give anyone who wants to try remote access to my machine.

**Comment by phelixbtc** [comment]
Is this obsolete? Looks overly complicated.

**Comment by JeremyRand** [comment]
@phelixbtc Last I heard OS X building was still messed up in the main repo, which this PR is supposed to fix.  So it's still relevant, but I'm not sure if @indolering had any luck verifying that this PR works.

**Comment by indolering** [comment]
I can get it to built the non-qt version which is a major improvement.  Others can get this to build on Linux and Windows then I would support accepting the pull request.

**Comment by indolering** [comment]
Figured out what's wrong with 10.9, just linking these here for future reference:

https://github.com/bitcoin/bitcoin/issues/2806
https://github.com/bitcoin/bitcoin/issues/3228
https://github.com/bitcoin/bitcoin/issues/3291

@phelixbtc Are you able to get this to build on Windows?  Can someone with a local Ubuntu install try it out?

**Comment by phelixbtc** [comment]
Autotools on windows is somewhat inconvenient to install so I'd rather not try but stick to easywinbuilder which is a piece of cake.

**Comment by indolering** [comment]
If we are basing on Libcoin, this just doesn't make any sense.  I really want to get it building on my own machine so we can have an official binary but now there is some sort of issue with 10.9.  I will try one more time on my older machine using 10.8.

Anyway, @domob1812, I'm voting to reject this pull request, I can maintain my own fork and provide binaries from that until the Libcoin rebase is finished.

**Pull request closed without merging**
