### PR TITLE
Qt5 EasyWinBuilder

### PR DESCRIPTION
**Pull request by phelixbtc**
Fix EasyWinBuilder because of removed downloads. Switch to Qt5 and MinGW4.8.2. Cleanup.

### CODE REVIEW

**Comment by domob1812** [comment]
Looks good, but I don't want to merge it myself.  I can't test this (obviously) and since EasyWinBuilder is kind of "your project", I think it is fine for you to merge yourself when you think that everything is ready and works.  But if some other Windows user can test it, this may be a good idea to do first.

**Comment by phelixbtc** [comment]
Snailbrain tested and it worked. Also it worked for me on two machines. Merging.

**Comment by chronokings** [comment]
APOLOGIES.. compiled fine. Crashes instantly when run.
tried renaming datadir.. same issue.
Daemon and qt both crash.
nothing in log.

**Comment by phelixbtc** [comment]
Merging since it works at least for me on three machines and the old one does not work at all any more because of some files not being publicly available any more.

**Pull request merged**
